/**
 * trap-writer.ts
 *
 * Template-based Drosera Trap generator.
 * No API calls, no API key, no external dependencies.
 *
 * How it works:
 *  1. Detect which trap PATTERN fits the description (keyword matching)
 *  2. Fill the matching template with user-provided values
 *  3. Return valid, compilable Solidity + drosera.toml
 *
 * Templates:
 *  - ownership    → monitors if owner/admin address changes
 *  - balance      → monitors ETH balance drops below threshold
 *  - erc20supply  → monitors ERC20 totalSupply changes
 *  - erc20balance → monitors ERC20 token balance of an address
 *  - paused       → monitors if a protocol's paused state changes
 *  - threshold    → monitors any uint256 value against a threshold
 *  - drop         → monitors a value for a sudden % drop across blocks
 *  - custom       → generic fallback template with clear TODOs
 */

// ── Types ──────────────────────────────────────────────────────────────────

export interface TrapInput {
  description: string;
  contractAddress?: string;
  contractAbi?: string;
  blockSampleSize?: number;
}

export interface GeneratedTrap {
  contractName: string;
  pattern: string;
  solidityCode: string;
  explanation: string;
  suggestedToml: string;
  warnings: string[];
}

// ── Pattern detection ──────────────────────────────────────────────────────

type PatternKey = "ownership" | "balance" | "erc20supply" | "erc20balance" | "paused" | "threshold" | "drop" | "custom";

function detectPattern(desc: string): PatternKey {
  const d = desc.toLowerCase();
  if (/owner|admin|access control|role|signer/.test(d))     return "ownership";
  if (/paused|pause|unpause|frozen|freeze/.test(d))          return "paused";
  if (/total.?supply|mint|burn|supply.change/.test(d))       return "erc20supply";
  if (/erc20|token.balance|token.amount/.test(d))            return "erc20balance";
  if (/eth.balance|native.balance|ether.balance/.test(d))    return "balance";
  if (/drop|decrease|fall|crash|sudden|spike/.test(d))       return "drop";
  if (/threshold|below|above|exceed|limit|cap/.test(d))      return "threshold";
  return "custom";
}

// ── Name generator ─────────────────────────────────────────────────────────

function buildContractName(pattern: PatternKey, desc: string): string {
  const words = desc
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .split(" ")
    .filter(Boolean)
    .slice(0, 3)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());

  const suffix = "Trap";
  return words.join("") + suffix;
}

function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "");
}

// ── TOML builder ───────────────────────────────────────────────────────────

function buildToml(contractName: string, blockSampleSize: number, contractAddress?: string): string {
  return [
    `# drosera.toml — generated by drosera-mcp-server`,
    `# Fill in eth_rpc_url, response_contract, and response_function before deploying.`,
    ``,
    `[drosera]`,
    `eth_rpc_url = "https://rpc.hoodi.ethpandaops.io"  # replace with your RPC`,
    ``,
    `[traps.${toSnakeCase(contractName)}]`,
    `path = "out/${contractName}.sol/${contractName}.json"`,
    `response_contract = "${contractAddress ?? "0xYOUR_RESPONSE_CONTRACT"}"`,
    `response_function = "YOUR_RESPONSE_FUNCTION()"`,
    `block_sample_size = ${blockSampleSize}`,
    `min_number_of_operators = 1`,
    `max_number_of_operators = 5`,
    `private_trap = false`,
  ].join("\n");
}

// ── TEMPLATES ──────────────────────────────────────────────────────────────

function templateOwnership(name: string, address: string): string {
  return `// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "drosera-contracts/interfaces/ITrap.sol";

interface IOwnable {
    function owner() external view returns (address);
}

/// @title ${name}
/// @notice Monitors the owner() of a contract and triggers if it changes.
/// @dev Implements the Drosera ITrap interface.
contract ${name} is ITrap {

    /// @notice The contract whose ownership is being monitored.
    address public constant TARGET = ${address};

    /// @notice The expected owner address. Update this before deploying.
    address public constant EXPECTED_OWNER = 0x0000000000000000000000000000000000000000; // TODO: set expected owner

    struct Snapshot {
        address owner;
    }

    /// @inheritdoc ITrap
    /// @dev Reads the current owner every block.
    function collect() external view returns (bytes memory) {
        address currentOwner = IOwnable(TARGET).owner();
        return abi.encode(Snapshot({ owner: currentOwner }));
    }

    /// @inheritdoc ITrap
    /// @dev Triggers if the owner no longer matches EXPECTED_OWNER.
    function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory) {
        if (data.length == 0) return (false, bytes(""));

        Snapshot memory latest = abi.decode(data[0], (Snapshot));

        if (latest.owner != EXPECTED_OWNER) {
            return (true, abi.encode("Owner changed unexpectedly", latest.owner));
        }

        return (false, bytes(""));
    }
}`;
}

// ─────────────────────────────────────────────────────────────────────────

function templateBalance(name: string, address: string): string {
  return `// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "drosera-contracts/interfaces/ITrap.sol";

/// @title ${name}
/// @notice Monitors the ETH balance of TARGET and triggers if it drops below THRESHOLD.
contract ${name} is ITrap {

    /// @notice The address whose ETH balance is monitored.
    address public constant TARGET = ${address};

    /// @notice Minimum acceptable ETH balance (in wei). Update before deploying.
    uint256 public constant THRESHOLD = 1 ether; // TODO: set your threshold

    struct Snapshot {
        uint256 balance;
    }

    /// @inheritdoc ITrap
    function collect() external view returns (bytes memory) {
        return abi.encode(Snapshot({ balance: TARGET.balance }));
    }

    /// @inheritdoc ITrap
    /// @dev Triggers if balance drops below THRESHOLD.
    function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory) {
        if (data.length == 0) return (false, bytes(""));

        Snapshot memory latest = abi.decode(data[0], (Snapshot));

        if (latest.balance < THRESHOLD) {
            return (true, abi.encode("ETH balance below threshold", latest.balance));
        }

        return (false, bytes(""));
    }
}`;
}

// ─────────────────────────────────────────────────────────────────────────

function templateErc20Supply(name: string, address: string): string {
  return `// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "drosera-contracts/interfaces/ITrap.sol";

interface IERC20 {
    function totalSupply() external view returns (uint256);
}

/// @title ${name}
/// @notice Monitors the totalSupply of an ERC20 token.
/// @dev Triggers if supply changes by more than CHANGE_THRESHOLD_BPS basis points in one block.
contract ${name} is ITrap {

    /// @notice The ERC20 token contract to monitor.
    address public constant TOKEN = ${address};

    /// @notice Max allowed supply change in basis points (100 = 1%). Update before deploying.
    uint256 public constant CHANGE_THRESHOLD_BPS = 1000; // 10% — TODO: adjust

    struct Snapshot {
        uint256 totalSupply;
    }

    /// @inheritdoc ITrap
    function collect() external view returns (bytes memory) {
        return abi.encode(Snapshot({ totalSupply: IERC20(TOKEN).totalSupply() }));
    }

    /// @inheritdoc ITrap
    /// @dev Compares the two most recent snapshots and triggers on large supply changes.
    function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory) {
        if (data.length < 2) return (false, bytes(""));

        Snapshot memory latest = abi.decode(data[0], (Snapshot));
        Snapshot memory prev   = abi.decode(data[1], (Snapshot));

        if (prev.totalSupply == 0) return (false, bytes(""));

        // Calculate absolute change in bps
        uint256 diff = latest.totalSupply > prev.totalSupply
            ? latest.totalSupply - prev.totalSupply
            : prev.totalSupply - latest.totalSupply;

        uint256 changeBps = (diff * 10_000) / prev.totalSupply;

        if (changeBps > CHANGE_THRESHOLD_BPS) {
            return (true, abi.encode("Total supply changed beyond threshold", changeBps));
        }

        return (false, bytes(""));
    }
}`;
}

// ─────────────────────────────────────────────────────────────────────────

function templateErc20Balance(name: string, tokenAddress: string): string {
  return `// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "drosera-contracts/interfaces/ITrap.sol";

interface IERC20 {
    function balanceOf(address account) external view returns (uint256);
}

/// @title ${name}
/// @notice Monitors the ERC20 token balance of a watched address.
/// @dev Triggers if the balance drops below MIN_BALANCE.
contract ${name} is ITrap {

    /// @notice The ERC20 token contract.
    address public constant TOKEN = ${tokenAddress};

    /// @notice The address whose token balance is being watched.
    address public constant WATCHED_ADDRESS = 0x0000000000000000000000000000000000000000; // TODO: set address

    /// @notice Minimum acceptable token balance. Update before deploying.
    uint256 public constant MIN_BALANCE = 1000e18; // TODO: set threshold

    struct Snapshot {
        uint256 balance;
    }

    /// @inheritdoc ITrap
    function collect() external view returns (bytes memory) {
        return abi.encode(Snapshot({
            balance: IERC20(TOKEN).balanceOf(WATCHED_ADDRESS)
        }));
    }

    /// @inheritdoc ITrap
    function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory) {
        if (data.length == 0) return (false, bytes(""));

        Snapshot memory latest = abi.decode(data[0], (Snapshot));

        if (latest.balance < MIN_BALANCE) {
            return (true, abi.encode("Token balance below minimum", latest.balance));
        }

        return (false, bytes(""));
    }
}`;
}

// ─────────────────────────────────────────────────────────────────────────

function templatePaused(name: string, address: string): string {
  return `// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "drosera-contracts/interfaces/ITrap.sol";

interface IPausable {
    function paused() external view returns (bool);
}

/// @title ${name}
/// @notice Triggers if the protocol becomes paused unexpectedly.
contract ${name} is ITrap {

    /// @notice The pausable contract to monitor.
    address public constant TARGET = ${address};

    struct Snapshot {
        bool paused;
    }

    /// @inheritdoc ITrap
    function collect() external view returns (bytes memory) {
        return abi.encode(Snapshot({ paused: IPausable(TARGET).paused() }));
    }

    /// @inheritdoc ITrap
    /// @dev Triggers the moment the protocol becomes paused.
    function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory) {
        if (data.length == 0) return (false, bytes(""));

        Snapshot memory latest = abi.decode(data[0], (Snapshot));

        if (latest.paused) {
            return (true, abi.encode("Protocol is paused"));
        }

        return (false, bytes(""));
    }
}`;
}

// ─────────────────────────────────────────────────────────────────────────

function templateThreshold(name: string, address: string): string {
  return `// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "drosera-contracts/interfaces/ITrap.sol";

interface ITarget {
    /// TODO: replace getValue() with the actual function name and signature
    function getValue() external view returns (uint256);
}

/// @title ${name}
/// @notice Monitors a uint256 value and triggers if it breaches a threshold.
contract ${name} is ITrap {

    address public constant TARGET = ${address};

    /// @notice The threshold value. Trigger fires when value drops BELOW this.
    uint256 public constant THRESHOLD = 0; // TODO: set your threshold

    struct Snapshot {
        uint256 value;
    }

    /// @inheritdoc ITrap
    function collect() external view returns (bytes memory) {
        return abi.encode(Snapshot({ value: ITarget(TARGET).getValue() }));
    }

    /// @inheritdoc ITrap
    function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory) {
        if (data.length == 0) return (false, bytes(""));

        Snapshot memory latest = abi.decode(data[0], (Snapshot));

        if (latest.value < THRESHOLD) {
            return (true, abi.encode("Value dropped below threshold", latest.value));
        }

        return (false, bytes(""));
    }
}`;
}

// ─────────────────────────────────────────────────────────────────────────

function templateDrop(name: string, address: string): string {
  return `// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "drosera-contracts/interfaces/ITrap.sol";

interface ITarget {
    /// TODO: replace getValue() with the actual function name
    function getValue() external view returns (uint256);
}

/// @title ${name}
/// @notice Monitors a value for a sudden percentage drop across blocks.
/// @dev Requires block_sample_size >= 2 in drosera.toml.
contract ${name} is ITrap {

    address public constant TARGET = ${address};

    /// @notice Maximum allowed drop in basis points before triggering (100 = 1%).
    uint256 public constant DROP_THRESHOLD_BPS = 2000; // 20% — TODO: adjust

    struct Snapshot {
        uint256 value;
    }

    /// @inheritdoc ITrap
    function collect() external view returns (bytes memory) {
        return abi.encode(Snapshot({ value: ITarget(TARGET).getValue() }));
    }

    /// @inheritdoc ITrap
    /// @dev data[0] = newest block, data[1] = previous block.
    function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory) {
        if (data.length < 2) return (false, bytes(""));

        Snapshot memory latest = abi.decode(data[0], (Snapshot));
        Snapshot memory prev   = abi.decode(data[1], (Snapshot));

        if (prev.value == 0) return (false, bytes(""));

        // Only check for drops (latest < prev)
        if (latest.value >= prev.value) return (false, bytes(""));

        uint256 dropBps = ((prev.value - latest.value) * 10_000) / prev.value;

        if (dropBps > DROP_THRESHOLD_BPS) {
            return (true, abi.encode("Sudden value drop detected", dropBps));
        }

        return (false, bytes(""));
    }
}`;
}

// ─────────────────────────────────────────────────────────────────────────

function templateCustom(name: string, address: string, description: string): string {
  return `// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "drosera-contracts/interfaces/ITrap.sol";

/// @title ${name}
/// @notice ${description}
/// @dev TODO: implement collect() and shouldRespond() for your specific use case.
contract ${name} is ITrap {

    /// @notice The contract to monitor. Update before deploying.
    address public constant TARGET = ${address};

    // TODO: define your Snapshot struct with the fields you want to capture
    struct Snapshot {
        uint256 value;   // replace with actual fields
        address addr;    // replace or remove
    }

    /// @inheritdoc ITrap
    /// @dev TODO: read the on-chain state you care about and encode it.
    function collect() external view returns (bytes memory) {
        // Example — replace with actual calls:
        // return abi.encode(Snapshot({ value: ITarget(TARGET).getValue(), addr: TARGET }));
        return abi.encode(Snapshot({ value: 0, addr: TARGET }));
    }

    /// @inheritdoc ITrap
    /// @dev TODO: decode data[0] and implement your trigger condition.
    function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory) {
        if (data.length == 0) return (false, bytes(""));

        Snapshot memory latest = abi.decode(data[0], (Snapshot));

        // TODO: replace this condition with your actual trigger logic
        if (latest.value == 0) {
            return (true, abi.encode("Condition met", latest.value));
        }

        return (false, bytes(""));
    }
}`;
}

// ── Main export ────────────────────────────────────────────────────────────

export function generateTrap(input: TrapInput): GeneratedTrap {
  const {
    description,
    contractAddress = "0x0000000000000000000000000000000000000000",
    blockSampleSize = 2,
  } = input;

  const pattern = detectPattern(description);
  const contractName = buildContractName(pattern, description);
  const addr = contractAddress;

  const warnings: string[] = [];
  if (contractAddress === "0x0000000000000000000000000000000000000000") {
    warnings.push("Set the TARGET contract address before deploying.");
  }
  warnings.push("Set response_contract and response_function in drosera.toml.");
  warnings.push("Run `forge build` to compile, then `drosera test` to validate.");

  let solidityCode: string;
  let explanation: string;

  switch (pattern) {
    case "ownership":
      solidityCode = templateOwnership(contractName, addr);
      explanation = `Monitors the owner() of ${addr} every block. Triggers if the owner changes from EXPECTED_OWNER. Set EXPECTED_OWNER to the legitimate owner address before deploying.`;
      warnings.push("Set EXPECTED_OWNER to the legitimate owner address in the contract.");
      break;

    case "balance":
      solidityCode = templateBalance(contractName, addr);
      explanation = `Monitors the ETH balance of ${addr} every block. Triggers if the balance drops below THRESHOLD (default 1 ETH). Adjust THRESHOLD to your needs.`;
      warnings.push("Set THRESHOLD to your minimum acceptable ETH balance (in wei).");
      break;

    case "erc20supply":
      solidityCode = templateErc20Supply(contractName, addr);
      explanation = `Monitors the totalSupply() of the ERC20 token at ${addr}. Triggers if supply changes by more than CHANGE_THRESHOLD_BPS basis points in a single block. Requires block_sample_size >= 2.`;
      warnings.push("Adjust CHANGE_THRESHOLD_BPS (default 1000 = 10%).");
      break;

    case "erc20balance":
      solidityCode = templateErc20Balance(contractName, addr);
      explanation = `Monitors the ERC20 token balance of WATCHED_ADDRESS for the token at ${addr}. Triggers if the balance drops below MIN_BALANCE.`;
      warnings.push("Set WATCHED_ADDRESS to the address you want to monitor.");
      warnings.push("Set MIN_BALANCE to the minimum acceptable token balance.");
      break;

    case "paused":
      solidityCode = templatePaused(contractName, addr);
      explanation = `Monitors the paused() state of the protocol at ${addr}. Triggers the moment the protocol becomes paused — useful for detecting emergency shutdowns or exploits.`;
      break;

    case "threshold":
      solidityCode = templateThreshold(contractName, addr);
      explanation = `Monitors a uint256 value from ${addr} every block. Triggers if the value drops below THRESHOLD. Replace getValue() with the actual function you want to monitor.`;
      warnings.push("Replace getValue() with the actual function name from your target contract.");
      warnings.push("Set THRESHOLD to the minimum acceptable value.");
      break;

    case "drop":
      solidityCode = templateDrop(contractName, addr);
      explanation = `Monitors a value from ${addr} for sudden percentage drops across blocks. Triggers if the value drops by more than DROP_THRESHOLD_BPS basis points in a single block. Requires block_sample_size >= 2.`;
      warnings.push("Replace getValue() with the actual function name.");
      warnings.push("Adjust DROP_THRESHOLD_BPS (default 2000 = 20%).");
      break;

    default:
      solidityCode = templateCustom(contractName, addr, description);
      explanation = `Generic trap template for: "${description}". The collect() and shouldRespond() functions have clear TODO comments — fill them in based on what you want to monitor.`;
      warnings.push("This is a generic template. Implement collect() and shouldRespond() for your use case.");
      break;
  }

  const suggestedToml = buildToml(contractName, blockSampleSize, contractAddress);

  return {
    contractName,
    pattern,
    solidityCode,
    explanation,
    suggestedToml,
    warnings,
  };
}